### ISSUE TITLE
OMG! it's panic

### ISSUE THREAD

**Issue by beaquant** [dgrr/http2#58]
panic: send on closed channel

goroutine 57799 [running]:
github.com/dgrr/http2.(*Ctx).resolve(0x40f3b6, {0xcc4820, 0xc00008a070})
        /root/gopath/pkg/mod/github.com/dgrr/http2@v0.3.4/client.go:58 +0x36
github.com/dgrr/http2.(*Conn).writeLoop.func2.1({0x445d4f, 0xc000682f70}, {0xb1f200, 0xc000b03ce0})
        /root/gopath/pkg/mod/github.com/dgrr/http2@v0.3.4/conn.go:414 +0x3d
sync.(*Map).Range(0xc000682f90, 0xc000682e78)
        /root/go/src/sync/map.go:346 +0x2aa
github.com/dgrr/http2.(*Conn).writeLoop.func2()
        /root/gopath/pkg/mod/github.com/dgrr/http2@v0.3.4/conn.go:412 +0x1bd
github.com/dgrr/http2.(*Conn).writeLoop(0xc001b98b40)
        /root/gopath/pkg/mod/github.com/dgrr/http2@v0.3.4/conn.go:471 +0x407
created by github.com/dgrr/http2.(*Conn).Handshake
        /root/gopath/pkg/mod/github.com/dgrr/http2@v0.3.4/conn.go:239 +0x7b

**Comment by dgrr** [comment]
Sad story. I'll take a look as soon as I can. Thanks for reporting.

**Comment by dgrr** [comment]
Looks like there's a race condition there. The channel is closed because the response has been resolved already.

**Comment by hiqsociety** [comment]
my level can only think of mutex to resolve this. it's not elegant but will do for now? a quick fix thing.

**Comment by trajan0x** [comment]
https://github.com/diamondcdn/fasthttp-http2 Fixes this
